using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LevelConfigs
{
    public static List<LevelConfig> levelConfigs;

    static LevelConfigs()
    {
        levelConfigs = new List<LevelConfig>();
        InitializeDefaultLevels();
    }

    private static void InitializeDefaultLevels()
    {
        // 测试关
        levelConfigs.Add(new LevelConfig
        {
            levelID = 0,
            levelName = "Test",
            nextLevelID = new List<int> { 1 },
            awardPlantID = PlantID.None,
            awardPropID = PropID.Note,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = false,
            startingSun = 8000,
            cardType = TypeOfCard.Fixation,
            fixedCards = new List<PlantID> { PlantID.CherryBomb, PlantID.PotatoMine, PlantID.Chomper, PlantID.TallNut, PlantID.Pumpkin },

            zombieID = new List<ZombieID> { ZombieID.PoleVaultingZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false},
                },
            spawnTimer = 30.0f,
            cardCoolingDown = false,
        });
        // 1-1
        levelConfigs.Add(new LevelConfig
        {
            levelID = 1,
            levelName = "1-1",
            nextLevelID = new List<int> { 2 },
            awardPlantID = PlantID.Sunflower,
            mapID = 1,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 150,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> {ZombieID.NormalZombie},
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 2.0f,largeWave = false},
            },
        });
        // 1-2
        levelConfigs.Add(new LevelConfig
        {
            levelID = 2,
            levelName = "1-2",
            nextLevelID = new List<int>{ 3 },
            awardPlantID = PlantID.CherryBomb,
            mapID = 2,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> {ZombieID.NormalZombie},
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 2.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 2.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 2.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 6.0f,largeWave = true},
            },
        });
        // 1-3
        levelConfigs.Add(new LevelConfig
        {
            levelID = 3,
            levelName = "1-3",
            nextLevelID = new List<int> { 4 },
            awardPlantID = PlantID.WallNut,
            mapID = 2,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 2.0f,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 8.0f,largeWave = true,certainlySpawn=1},
            },
        });
        // 1-4
        levelConfigs.Add(new LevelConfig
        {
            levelID = 4,
            levelName = "1-4",
            nextLevelID = new List<int> { 5 },
            awardPlantID = PlantID.None,
            awardPropID = PropID.Shovel,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 2.0f,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 5.0f,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 10.0f,largeWave = true,certainlySpawn=1},
            },
        });
        // 1-5
        levelConfigs.Add(new LevelConfig
        {
            levelID = 5,
            levelName = "1-5",
            nextLevelID = new List<int> { 6 },
            awardPlantID = PlantID.PotatoMine,
            awardPropID = PropID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_loon,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingRedWallNut },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 15,largeWave = true,certainlySpawn=1},
            },
            shovel = false,
            spawnTimer = 30.0f,
            restrictedArea = 3,
        });
        // 1-6
        levelConfigs.Add(new LevelConfig
        {
            levelID = 6,
            levelName = "1-6",
            nextLevelID = new List<int> { 7 },
            awardPlantID = PlantID.SnowPea,
            awardPropID = PropID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 10,largeWave = true,certainlySpawn=2},
            },
        });
        // 1-7
        levelConfigs.Add(new LevelConfig
        {
            levelID = 7,
            levelName = "1-7",
            nextLevelID = new List<int> { 8 },
            awardPlantID = PlantID.Chomper,
            awardPropID = PropID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 2,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 10,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 20,largeWave = true,certainlySpawn=2},
            },
        });
        // 1-8
        levelConfigs.Add(new LevelConfig
        {
            levelID = 8,
            levelName = "1-8",
            nextLevelID = new List<int> { 9 },
            awardPlantID = PlantID.Repeater,
            awardPropID = PropID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 10,largeWave = true,certainlySpawn=1},
            },
        });
        // 1-9
        levelConfigs.Add(new LevelConfig
        {
            levelID = 9,
            levelName = "1-9",
            nextLevelID = new List<int> { 10 },
            awardPlantID = PlantID.None,
            awardPropID = PropID.Note,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 10,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 20,largeWave = true,certainlySpawn=2},
            },
        });
        // 1-10
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10,
            levelName = "1-10",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.None,
            awardPropID = PropID.MiniGame,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_ultimateBattle,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.PeaShooter, PlantID.CherryBomb, PlantID.WallNut, PlantID.PotatoMine, PlantID.SnowPea, PlantID.Chomper, PlantID.Repeater},

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 7,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 20,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 18,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 19,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 20,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 21,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.NormalZombie},spawnWeight = 40,largeWave = true,certainlySpawn=2},
            },
            spawnTimer = 30.0f,
        });
        // 内测专属-此路不通
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10001,
            levelName = "内测专属-此路不通",
            nextLevelID = new List<int> {},
            awardPlantID = PlantID.TallNut,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Fixation,
            fixedCards = new List<PlantID> { PlantID.PeaShooter, PlantID.Sunflower, PlantID.CherryBomb, PlantID.WallNut, PlantID.TallNut },

            zombieID = new List<ZombieID> { ZombieID.ConeHeadZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 10,largeWave = true},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie},spawnWeight = 20,largeWave = true},
            },
        });
        // 内测专属-咣咣铛铛
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10002,
            levelName = "内测专属-咣咣铛铛",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.Pumpkin,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Fixation,
            fixedCards = new List<PlantID> { PlantID.PeaShooter, PlantID.Sunflower, PlantID.CherryBomb, PlantID.WallNut, PlantID.PotatoMine, PlantID.SnowPea, PlantID.Repeater, PlantID.Pumpkin },

            zombieID = new List<ZombieID> { ZombieID.BucketZombie, ZombieID.ScreenDoorZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 10,largeWave = true},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 20,largeWave = true},
            },
        });
        // 内测专属-僵尸快跑
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10003,
            levelName = "内测专属-僵尸快跑",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.GatlingPea,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_loon,
            dropSun = true,
            startingSun = 200,
            cardType = TypeOfCard.Autonomy,

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.PoleVaultingZombie, ZombieID.FootballZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.FootballZombie },spawnWeight = 2,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 3,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.PoleVaultingZombie, ZombieID.FootballZombie, ZombieID.NormalZombie},spawnWeight = 10,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.PoleVaultingZombie, ZombieID.FootballZombie, ZombieID.NormalZombie },spawnWeight = 20,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 13,largeWave = false },
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie },spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.FootballZombie, ZombieID.PoleVaultingZombie },spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.PoleVaultingZombie, ZombieID.FootballZombie, ZombieID.NormalZombie },spawnWeight = 30,largeWave = true,certainlySpawn=2},
            },
            spawnTimer = 25.0f,
            gameSpeed = 2.0f,
        });
        // 内测专属-全军出击
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10004,
            levelName = "内测专属-全军出击",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_ultimateBattle,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.PeaShooter, PlantID.CherryBomb, PlantID.WallNut, PlantID.SnowPea, PlantID.Chomper, PlantID.Repeater, PlantID.Torchwood, PlantID.TallNut, PlantID.Pumpkin, PlantID.GatlingPea },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = true},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.NormalZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.NormalZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 20,largeWave = true},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 12,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 13,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 17,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 18,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 19,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 20,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 40,largeWave = true},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 22,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 23,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 24,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 25,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 26,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 27,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 28,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 29,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 30,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.ScreenDoorZombie},spawnWeight = 60,largeWave = true},
            },
            spawnTimer = 28.0f,
        });
        // 内测专属-冰之歌
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10005,
            levelName = "内测专属-冰之歌",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Fixation,
            fixedCards = new List<PlantID> { PlantID.Sunflower, PlantID.CherryBomb, PlantID.WallNut, PlantID.SnowPea, PlantID.TallNut },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.ConeHeadZombie, ZombieID.NormalZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.NormalZombie},spawnWeight = 10,largeWave = true,certainlySpawn=3},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.NormalZombie},spawnWeight = 20,largeWave = true,certainlySpawn=3},
            },
        });
        // 内测专属-绝对火力
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10006,
            levelName = "内测专属-绝对火力",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.Torchwood,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Fixation,
            fixedCards = new List<PlantID> { PlantID.Sunflower, PlantID.WallNut, PlantID.PotatoMine, PlantID.Repeater, PlantID.Torchwood, PlantID.TallNut, PlantID.Pumpkin, PlantID.GatlingPea },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie },
            zombieWaves = new List<ZombieWave> {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 10,largeWave = true,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> { ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 20,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 30,largeWave = true,certainlySpawn=2},
            },
        });
        // 内测专属-保龄球1
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10007,
            levelName = "内测专属-保龄球1",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.BowlingWallNut,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_loon,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingRedWallNut },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie },
            zombieWaves = new List<ZombieWave>
            {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 15,largeWave = true,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 25,largeWave = true,certainlySpawn=1},
            },
            shovel = false,
            spawnTimer = 30.0f,
            restrictedArea = 3,
        });
        // 内测专属-保龄球2
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10008,
            levelName = "内测专属-保龄球2",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.BowlingRedWallNut,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_loon,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingRedWallNut },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie },
            zombieWaves = new List<ZombieWave>
            {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 15,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 30,largeWave = true,certainlySpawn=2},
            },
            shovel = false,
            spawnTimer = 30.0f,
            restrictedArea = 3,
        });
        // 内测专属-保龄球3
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10009,
            levelName = "内测专属-保龄球3",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.BowlingBigWallNut,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_loon,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingWallNut, PlantID.BowlingRedWallNut, PlantID.BowlingBigWallNut },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie },
            zombieWaves = new List<ZombieWave>
            {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.PoleVaultingZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.PoleVaultingZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie, ZombieID.PoleVaultingZombie},spawnWeight = 6,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 15,largeWave = true,certainlySpawn=3},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 8,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 25,largeWave = true,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 17,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 17,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 18,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.ScreenDoorZombie},spawnWeight = 35,largeWave = true,certainlySpawn=1},
            },
            shovel = false,
            spawnTimer = 30.0f,
            restrictedArea = 3,
        });
        // 内测专属-豌豆的假期
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10010,
            levelName = "内测专属-豌豆的假期",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.TwinSunflower,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_day,
            dropSun = true,
            startingSun = 50,
            cardType = TypeOfCard.Fixation,
            fixedCards = new List<PlantID> { PlantID.Sunflower, PlantID.CherryBomb, PlantID.PotatoMine, PlantID.Chomper, PlantID.TallNut, PlantID.Pumpkin, PlantID.TwinSunflower, PlantID.BowlingWallNut, PlantID.BowlingRedWallNut, PlantID.BowlingBigWallNut },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie },
            zombieWaves = new List<ZombieWave>
            {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 1,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 2,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.ScreenDoorZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 10,largeWave = true,certainlySpawn=2},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.PoleVaultingZombie, ZombieID.ConeHeadZombie, ZombieID.ScreenDoorZombie},spawnWeight = 6,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 6,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 20,largeWave = true,certainlySpawn=3},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 14,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 15,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie},spawnWeight = 16,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.ScreenDoorZombie, ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 30,largeWave = true,certainlySpawn=3},
            }
        });
        // 内测专属-自助餐
        levelConfigs.Add(new LevelConfig
        {
            levelID = 10011,
            levelName = "内测专属-自助餐",
            nextLevelID = new List<int> { },
            awardPlantID = PlantID.None,
            mapID = 3,
            time = TimeOfDay.Day,
            music = ResourceConfig.music_loon,
            dropSun = false,
            startingSun = 0,
            cardType = TypeOfCard.Conveyor,
            fixedCards = new List<PlantID> { PlantID.Chomper, PlantID.Chomper, PlantID.Chomper, PlantID.CherryBomb, PlantID.WallNut, PlantID.Pumpkin },

            zombieID = new List<ZombieID> { ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie },
            zombieWaves = new List<ZombieWave>
            {
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 3,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie},spawnWeight = 4,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 4,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.PoleVaultingZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 5,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.FootballZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie},spawnWeight = 6,largeWave = false,certainlySpawn=1},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 7,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.FootballZombie},spawnWeight = 15,largeWave = true},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 8,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 9,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 10,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 11,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 12,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.BucketZombie, ZombieID.FootballZombie},spawnWeight = 13,largeWave = false},
                new ZombieWave {zombieIDs = new List<ZombieID> {ZombieID.BucketZombie, ZombieID.NormalZombie, ZombieID.ConeHeadZombie, ZombieID.PoleVaultingZombie, ZombieID.FootballZombie},spawnWeight = 30,largeWave = true},
            },
            spawnTimer = 30.0f,
        });
    }
}
